# Generated by Django 5.1.1 on 2024-12-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0002_remove_payment_created_at_payment_initiated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='initiated_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
