# Generated by Django 5.1.1 on 2024-10-09 10:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0004_submenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('preparation_time', models.CharField(blank=True, max_length=50)),
                ('serving_size', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('veg', 'VEG'), ('non_veg', 'NON VEG')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_available', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canteenapp.menu')),
                ('submenu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canteenapp.submenu')),
            ],
        ),
    ]
