# Generated by Django 5.1.1 on 2024-12-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0004_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
