# Generated by Django 5.1.1 on 2024-12-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0006_userfcmtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFCMToken',
        ),
    ]
