# Generated by Django 5.1.1 on 2024-10-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0007_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('GST', 'GST'), ('Delivery', 'Delivery Charge'), ('Service', 'Service Charge'), ('Packaging', 'Packaging Charge'), ('PlatFormFee', 'PlatForm Fee'), ('Other', 'Other')], default='GST', max_length=20)),
                ('value_type', models.CharField(choices=[('Price', 'Fixed Price'), ('Percentage', 'Percentage')], default='Price', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
