# Generated by Django 5.1.1 on 2024-10-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0009_order_orderitem_order_items_payment_order_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup'), ('dining', 'Dining')], default='pickup', max_length=20),
        ),
    ]
