# Generated by Django 5.1.1 on 2024-12-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0009_adminnotification_deliverypersonnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count',
            field=models.IntegerField(default=True, null=True),
        ),
    ]
