# Generated by Django 5.1.1 on 2024-12-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0010_item_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
