# Generated by Django 5.1.1 on 2024-12-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0011_alter_item_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_status',
            field=models.CharField(default='confirmed', max_length=20),
        ),
    ]
