# Generated by Django 5.1.1 on 2024-12-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0012_alter_order_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup'), ('dining', 'Dining'), ('pay_on_delivery', 'Pay On Delivery')], default='pickup', max_length=20),
        ),
    ]
