# Generated by Django 5.1.1 on 2024-12-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0013_alter_order_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
