# Generated by Django 5.1.1 on 2024-12-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0014_restaurant_restaurant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_pin',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
