# Generated by Django 5.1.1 on 2024-12-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0015_order_order_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_pin',
            field=models.IntegerField(null=True),
        ),
    ]
