# Generated by Django 5.1.1 on 2024-10-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0015_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
