# Generated by Django 5.1.1 on 2024-10-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0016_alter_order_customer_status_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location_image', models.ImageField(blank=True, null=True, upload_to='location_pics/')),
            ],
        ),
    ]
